apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapshot-validation-webhook.fullname" . }}
  labels:
    {{- include "snapshot-validation-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  selector:
    {{- include "snapshot-validation-webhook.selectorLabels" . | nindent 4 }}
---
