imagePullSecrets: {}

installation:
  controlPlaneTolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: "NoExecute"
  enabled: true
  kubeletVolumePluginPath: "None"
  kubernetesProvider: ''
  calicoNetwork:
    bgp: Disabled
  imagePath: "rancher"
  imagePrefix: "mirrored-calico-"
  flexVolumePath: "/var/lib/kubelet/volumeplugins/"

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Resource requests and limits for the tigera/operator pod.
resources: {}

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

# NodeSelector for the tigera/operator pod.
nodeSelector:
  kubernetes.io/os: linux

# Custom annotations for the tigera/operator pod.
podAnnotations: {}

# Custom labels for the tigera/operator pod.
podLabels: {}

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: rancher/mirrored-calico-operator
  version: v1.30.7
  registry: docker.io
calicoctl:
  image: rancher/mirrored-calico-ctl
  tag: v3.26.3

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

# Config required by Windows nodes
ipamConfig:
  strictAffinity: true
  autoAllocateBlocks: true

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
  defaultEndpointToHostAction: "Drop"
  logSeveritySys: "Info"
  xdpEnabled: true
