apiVersion: v1
description: eBPF-based Networking, Security, and Observability
home: https://cilium.io/
keywords:
- cilium
kubeVersion: '>= 1.12.0-0'
maintainers:
- email: charts@rancher.com
  name: Rancher Labs
name: rke2-cilium
sources:
- https://github.com/rancher/rke2-charts
version: 1.11.101
